name: publish to nuget
on:
  push:
    branches:
      - master # Default release branch
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Publish
      - name: publish on version change
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: Dependencies.csproj
          PACKAGE_NAME: Dependencies
          TAG_COMMIT: true
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
