name: Tests
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: build and Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal
        
      - name: publish on version change
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: Dependencies/Dependencies.csproj
          PACKAGE_NAME: Dependencies
          TAG_COMMIT: true
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
